services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8081:8080"
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          memory: 64M
