name: deploy
on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT || 22 }}" -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
      - name: Run remote deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY:  ${{ secrets.SSH_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT || 22 }}
        run: |
          echo "$SSH_KEY" > key && chmod 600 key
          ssh -i key -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "~/deploy/deploy.sh"
